### ISSUE TITLE
Skirting Fees

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/allo-v2#5] opened 2023-06-19 13:22 UTC
from @zobront 
Starting a thread for us to discuss the fee skirting issue. The issue is that, since projects choose their own strategies, we can't have Allo protocol fees taken on the strategy, or users can easily skirt it. It needs to live on the core Allo.sol contract, but that poses challenges because when fees are taken may not be consistent across projects.

**CURRENT WORKING SOLUTION**

1) When a pool operator calls `createPool()`, they can add tokens and a fee is taken directly at that point. The total balance with which the pool has been funded is stored in the Allo.sol contract.

2) At any point, the operator can all `fundPool()` and add additional funds, and fees are taken at that point. The total balance with which the pool has been funded is updated in the Allo.sol contract.

3) When users call `allocate()` in a strategy that requires them to send additional funds (ie Quantitative Funding), that can be handled in two ways:
    a) If the funds go directly to the recipient, our prebuilt strategies take the fee directly at that point. If they deploy their own strategy, they could skirt this fee.
    b) If the funds go into the distribution strategy for later distribution, a function is called on Allo.sol that updates the total funding amount for the pool and takes the fee.

4) In order to trigger payouts, we call `finalize()` on Allo.sol. This checks the balance of the distribution strategy and, if it is greater than the stored amount of what it should be, takes any excess balance and transfers it to the Allo treasury. 

**ISSUES**

1) An allocation strategy can be written that sends allocations straight to the recipient and pays no fees.

2) A distribution strategy can be written that skips over the `finalize()` function. We could add a flag to the main contract that is is now `claimable` once `finalize()` is called (which would stop claimers from using the core contract's `claim()` function if their distribution strategy skirts this step) but even that isn't perfect, because it doesn't account for distributions with ongoing phases.

___

from @KurtMerbeth 

Additional Question, since we will have Pools with and without distribution strategies:
Are we taking only fees from the distribution, or also from allocations? @nfrgosselin 

___

from @thelostone-mc 

How would we ensure that the funds aren't sent directly to the DistributionStrategy and bypass the fundPool function ?

___

from @codenamejason 

Can we do this by only allowing the Allocation Strategy to know the Distribution Strategy address or interact with the Distribution Strategy as the only owner? @thelostone-mc

___

from @nfrgosselin 

> Additional Question, since we will have Pools with and without distribution strategies:

Can you say more @KurtMerbeth? What types of pools wouldn't have distribution strategies?

> Are we taking only fees from the distribution, or also from allocations?

My thinking was that the **protocol** would only take fees from the core pool (i.e. the distribution). Allocations could become separate income streams for **strategy developers** if they're creating novel strategies. So Gitcoin could deploy QF strategies that we technically take fees from, but for pools using those strategies we would actually be making fees on the distribution _and_ the allocation. Another scenario are pools using externally-developed strategies, where the protocol would collect fees on the distribution and the strategy develop would collect fees on the allocation.

**Comment by zobront** [comment] 2023-06-26 14:59
I've spent a lot more time thinking about this and I don't think any version of the above strategy will get us 100% there. 

There are tons of ways to block this behavior:
- using a tracked balance instead of `balanceOf()`
- creating economic incentives for users to send excess funds to treasury
- etc

The problem is that inherently, all of them require the strategy to cooperate. If someone is willing to create a rogue strategy, they can skip all of that, and there's no way I can see to verify it on chain. We can make it more inconvenient, but they can ultimately always make the strategy do whatever they want.

**The only solution I can see is to involve off-chain watchers to help.**

Here is my thinking:
- we track in Allo.sol the total amount sent to a distribution strategy via `createPool` and `fundPool`
- when enforce the rule that, if an allocation strategy needs to send funds to a distribution strategy, it does it via a call to `Allo.sol#fundPool()`, meaning that they don't need to implement fees, they happen automatically
- part of the distribution strategy interface is a `skim()` function that takes the difference between the current balance of the distribution strategy and the amount tracked in Allo.sol and sends it to the treasury
- the off chain watcher monitors for balance changes in the asset. if it ever sees a balance chance that did NOT come from `Allo.sol#fundPool()`, it tries to call `skim()`. if `skim()` doesn't succeed at lowering the balance down to the tracked amount, the strategy is added to the blacklist on Allo.sol
- this blacklist is checked in all functions that come through Allo.sol, so stops the core contract from being used by any users of the pool

What do you think? It's a bit messy, but it's the only possibility I can see that actually stops them. Anything that relies fully on on chain logic and economic incentives can be skirted by just not following the rules.

**Comment by zobront** [comment] 2023-06-26 19:47
Thinking more about this, one possible attack I could see is:
- I sent $1 to a strategy
- Off chain watcher calls `skim()`
- I backrun the `skim()` call with sending another $1, ensuring it's there by the end of the block
- Then, by the time the watcher sees things update, the balance is still off, and strategy gets added to blacklist

I think we'd need a way for the watcher to simulate the transaction or something to make this work. I don't have experience with this but can ask around.

**Comment by zobront** [comment] 2023-07-12 13:30
I think I have this part solved in a way that's much more elegant.

Instead of pushing the logic to the off chain watcher, we can have an on chain contract that can perform the logic atomically, and the off chain watcher just calls that.

```solidity
contract Watcher {
    function report(address strategy, address token) external returns (bool) {
        // pseudocode
        before = token.balanceOf(strategy);
        treasuryBefore = token.balanceOf(alloTreasury);
        reported = allo.fundedAmount(strategy);

        try strategy.skim(token) {
            if (token.balanceOf(strategy) != reported || token.balanceOf(treasury) != treasuryBefore + before - reported) {
                allo.addToBlocklist(strategy);
                return false;
            }
        } catch {
            allo.addToBlocklist(strategy);
            return false;
        }
        return true;
}
```

This basically ensures that the `skim()` function is working as intended, and automatically adds them to the blocklist if it doesn't.

Then, we can:

1) Have an off chain watcher that, when new pools are created, runs a simulation to send tokens to the strategy, call this watcher, and make sure that it returns true (ie it's working properly).

2) Have an off chain watcher (or build an incentive into the function above for others to have watcher bots) that watch for all tokens transferred into the contract, check the amount funded through Allo.sol, and calls this function if there's a discrepancy.

***

This addresses the issue in the way I discussed above, but without the risk of backrunning I described, and also dramatically simplifies the off chain logic by putting the actual checks and blacklisting on chain.

**Closed** 2023-07-28 05:54 UTC
